### ISSUE TITLE
Mob Suggestion: 2-3 headed dragons

### ISSUE THREAD

**Issue by GioTM** [AlexModGuy/Ice-and-Fire-Suggestions#102]
Maybe there could be a type of 2-headed or 3-headed dragon type, it could come in both ice or fire, and would be able to breathe those elements from all heads or only one of them, or it could have absolutely no breathing capabilities, but it could be a meele-only dragon, flying around, and bitting things to death, it would walk like the normal dragons, and it's nests would be very, veeery rare, being as rare as strongholds or even rarer, maybe it could also be very, very big, being able to be seen from very far away during the day, so attacking another player's base would be more advisable during the night, they could also have only dark colors, like black and navy blue, maybe dark red

hope this can be helpful in some way

**Comment by LordDecay26** [comment]
i like this idea, though maybe no mechanics should be changed with multi-headed dragons and rather it could just be an interesting, albeit rare, treat, to sometimes find regular ice and fire dragons with more than one head, like a rare mutation

**Comment by GioTM** [comment]
maybe, but I feel like 3 heads spitting fire/ice at the same time could become pretty op, if someone gets one of them, so I felt like the 2/3+ headed dragons would be much bigger and have much more hp, but be meele only, so it is somewhat balanced, since it would do mad damage, and so should be easier to intercept n' shit... sooo.. yeah, but I mean, your idea could also work I guess
