### ISSUE TITLE
New Mob Idea: Direwolf

### ISSUE THREAD

**Issue by TheColeMiner12** [AlexModGuy/Ice-and-Fire-Suggestions#103]
Hey, I don't know how many people have suggested this, but, following the  Game of Thrones series, a new creature that could be added could be the Direwolf  (Fantasy, not prehistoric). I know the mod creators are probably too busy with other parts of the mod to start it immediately, but here me out. Direwolves would be far rarer than their smaller relatives, and have different proportions (Longer snout, longer legs, slimmer build). Though  they are weaker than the other mythical beasts that roam the Overworld, they are still a formidable foe , and combating them with anything less than diamond armor would mean almost certain death. Adults are too wild in nature to be tamed, but imprinting on a pup  to raise it is possible. Once domesticated, these colossal canines are the most loyal companion one can find, and are rideable in adulthood. Just like Gray Wolves, they hunt in packs, but are able to attack larger prey for food (cows, horses). Should a beast be slain, its pelt can be crafted into a noble coat for only the most daring. Again, the devs probably do not have time for this, seeing all the other amazing things they are planning, but I would like to see this thing in a mod for once.

**Comment by Volkosoby** [comment]
I really hope Dire wolves get added at some point.
