### ISSUE TITLE
Becoming "The Blood of the Dragon"

### ISSUE THREAD

**Issue by NoahMeh** [AlexModGuy/Ice-and-Fire-Suggestions#104]
I just read a super intersting theory about how the Valyrians became the Blood of the Dragon. Remember in Season 1 when a Witch tricked Dany to sacrifice her unborn son for the life of Khal Drogo and she later had to kill him? She burned him and the Witch, so she got her Dragons to live and some People speculate that the life of Khal Drogo, Rhaego (her unborn son) and the Witch are actually in the Dragons, and that something Simillar might also work the other way around. Meaning that once maybe, a Valyria Woman lost her child while pregnancy or that the child was Born dead, so a Priester sacrificed a Dragon and putting his "life energy" into that of the Baby, The Baby opened his eyes and they were purple, he grew up to have silvery blond hair, making him the First who gains the title "Blood of the Dragon"

So how could we implement that into the game. So of Course you would Need to kill a Dragon and somepoint. Maybe making some sort of Mixture with a Dragon Heart, Dragon Blood, -Skull and -Bones. Then you would Need to performe some sort of ritual, the Screen would go black and you would "Wake up" again, beeing either "Blood of Fire" or "Blood of Ice". As a Blood of fire you would get a unlimited amount of fire resitence and as a Blood of ice you would get some sort of Frost resitence. The Dragons of your blood wouldn't attack you anymore, and by feeding them alot of Food, you could even tame a wild Dragon.

**Comment by TheLastCookie11** [comment]
nice idea i like it
