### ISSUE TITLE
old

### ISSUE THREAD

**Issue by Dejeh** [AlexModGuy/Ice-and-Fire-Suggestions#1101]
old

**Comment by Dragonair1124** [comment]
or maybe if the gorgon's blood can be taken if u use a bottle before the body dissapears . then gorgon's blood infused with enchanted golden apple.

**Comment by Dejeh** [comment]
old

**Comment by LAB5565** [comment]
So, either a one time weapon which can basically turn anything it's used on to stone, or a magical flying horse which can soar to the heavens and become a constellation...
I'll just get both.
