### ISSUE TITLE
mermaids AI suggestion

### ISSUE THREAD

**Issue by mser7** [AlexModGuy/Ice-and-Fire-Suggestions#117]
A way for the mermaid to make players to "forgot their urgent tasks"

- First, the mermaids sit on the shore of beaches or whatever they're spawned in, but it should be near water.
- Then they will detect if a player is presented in a vicinity, then they will start singing, (which can be hear from further distance, like how Ghasts cry can be hear across the Nether) shifting the player focus.
- Then, when the player found, or eventually found them and try to approach them, they will simultaneously jump into nearby waters then splashes away.
- The player may then want to capture them, which require him to chase after them, but this prove to be futile as the mermaid constantly splash away, while being near the water surface, and giggling as the same time, indicating they're having fun and to taunt the player more, they should be faster then vanilla boats.
- If the player choose to give up and go away, then after they went away for a short distance, the mermaids will reassemble again in a shore(prob require AI to pick out sand blocks near water) and start singing, taunting players even more. If the players choose to ignore them in the first place, then nothing will happens.
- Finally, the cycle repeats itself if the player decided to pursuit the mermaids again.

There should be a way for player to actually catch up to a mermaid, like if shes injured enough, she will slowed down and eventually can't swim. Or if they're satisfied enough, they will eventually decide to befriend you, and won't run away anymore.

- Mermaids won't attempt to run away from players in Creative, or if theres no water presented nearby, since they can't swim away.
- Mermaids should dive down water when sunset, and come on shore again tomorrow, preferably after quite a while after sunset to minimizing the chance the AI conflict with early sleeping. They should also run away when hostile mobs are nearby.

**Comment by GioTM** [comment]
yes! and while mermaids come up in the day, nagas should come up in the night! its perfect!

**Comment by AlexModGuy** [comment]
we've already planned their behavior

**Comment by AlexModGuy** [comment]
we've already planned their behavior
