### ISSUE TITLE
Hippogryph goes invisible and intangible above y=1500

### ISSUE THREAD

**Issue by darthvader45** [AlexModGuy/Ice-and-Fire-Suggestions#1273]
Apparently, if you fly too high with one, they go invisible and dismount you.  This means that you'd have to relog in order to not only see them again but also get back on.  I've had this happen multiple times.

**Comment by Aceplante** [comment]
that sounds like a bug not a suggestion

**Comment by darthvader45** [comment]
Whoops, wrong place.
