### ISSUE TITLE
Biome Compatibility with Oh The Biomes You'll Go, and Biomes O' Plenty

### ISSUE THREAD

**Issue by GordonRamsay20** [AlexModGuy/Ice-and-Fire-Suggestions#1292]
It's really annoying to just have a bland vanilla world, so we want to use biome mods. But we also want to use fire and ice, but a lot of things will not spawn in the biome of byg so... idk i just think yall should add compatibility for it.

**Comment by FireHDn** [comment]
I am playing in a 1.16.5 modpack Server, and there, ice and fire and Bioms o' plenty work fine with eachother
