### ISSUE TITLE
Dragon growing optional

### ISSUE THREAD

**Issue by mser7** [AlexModGuy/Ice-and-Fire-Suggestions#136]
A way to disable tamed dragons from growing since some people dislike laggy stage 5 dragons.
A new config optional that disable natural aging except for intervention with dragon meals. This option is located in the config of the mod, which make only way for dragon to becoming bigger and stronger is to be fed with dragon meals. You can fed your dragon until the size that you're consider "perfect" and have it remain that size forever, the only drawback is the dragon strength won't reached max potential.
This option is default "disable" in the config.

**Comment by mser7** [comment]
In response for "everything had to grow up", if you really want to be logical then you can set this feature to only work after a certain age, when a dragon is officially considered not a "baby" any more(have basic flight, basic attacks of adult dragons), the option will take effect at this point, and you are choose to feed your dragon to make it stronger, otherwise it will stay at that size forever.

**Comment by epicslayer999** [comment]
I agree with this. Like he said, this should be a config option disabled by default, but when enabled, dragons will only grow to around stage 3, maybe like 1/4 of the way into stage 3, and then stop. After that, dragons can grow beyond stage 3 by dragon meal or some other form of player input. Maybe the way for the game to detect when they're old enough for them to stop growing is when they're old enough to be ridden?
