### ISSUE TITLE
lava boulder class dragon 

### ISSUE THREAD

**Issue by zackyboy18** [AlexModGuy/Ice-and-Fire-Suggestions#14]
![wafp9up](https://cloud.githubusercontent.com/assets/27601074/25068454/af7d5ec6-22a7-11e7-889e-570e75886483.png)
a dragon like this but with some wing 
that eats lava to form boulders that spits boulders out as an attack 
and sleeps nearly all day

**Comment by AlexModGuy** [comment]
Sorry we only due creatures that have some basis already in some pre-existing cultural mythology.
