### ISSUE TITLE
[Suggestion] Idea to prevent dragon's from wandering far away from roost's.

### ISSUE THREAD

**Issue by Azormik** [AlexModGuy/Ice-and-Fire-Suggestions#143]
Hello, I am new to this mod but I have noticed that the dragons on the surface wander off far away from their roosts because of mobs, etc. which makes looting the treasure very easy. 

My idea is to make the roost's have the same effect as a village where the dragon's would only go a certain amount of blocks away from the center of the roost's and not go past that point and the center of the roost would act like a door so the dragon will occasionally go back to the center where all the treasure is. Similar to what a villager would do in a village full of doors. This would make looting the roost's more suspenseful and challenging because they will always be near by.

Adding a config for the roost "patrol area" radius would be a good idea too.

**Comment by GundunUkan** [comment]
In the 1.11.2 version of the mod dragons did stick around their rosts. I don't know why they no longer do, I hope it's a bug that will be fixed soon.
