### ISSUE TITLE
New Mob: Wyvern

### ISSUE THREAD

**Issue by Murbis1** [AlexModGuy/Ice-and-Fire-Suggestions#156]
A creature 3-5 Blocks high so not big look like a Dragon but the Body is more looking up the Tail smaller and longer Wings that can reach the Ground they live in Foresty Lands in caves  ( night they get back to there caves and Sleep there) they hunt with poison and can las

**Comment by Murbis1** [comment]
Can have a nest in there cave and if you get the Eggs out of there and kill the tanky mother you get wyvernmilk you need  to grow up the Baby wyverns.

**Comment by GundunUkan** [comment]
The devs already said wyverns aren't being added. Also, I'm guessing you got the inspiration for wyvern milk from ARK, but I think it should be something else, since wyverns are reptiles and the only animals that can produce milk are mammals.

**Comment by Murbis1** [comment]
GundunUkan that is not correct didnt you know that some birds feed there babys with milk too? like doven produce milk and give it thow the mouth to there children

**Comment by AguilaDaddy** [comment]
reptiles are not birds sorry to tell you murbis :/
