### ISSUE TITLE
Sexual dimorphism 

### ISSUE THREAD

**Issue by GundunUkan** [AlexModGuy/Ice-and-Fire-Suggestions#160]
Male and female dragons should have different textures so that scenarios like fighting a dragon for like an hour and in the end it turns out being a male and not dropping an egg, are brought down to minimum. It could be quite frustrating, indeed, so dragon sexual dimorphism should be a thing.

**Comment by PlatinumFox** [comment]
Or make male dragons stop growing at stage 3. Just their color would continue to darken as time went on. Only dark stage 3 would be found underground. Lairs could be more rare but if you saw a big dragon you would know it was female.

**Comment by unicorncatbug** [comment]
Or, Male dragons could have more defined features, perhaps more color on the facial region, like how some reptiles are today

**Comment by tillasiren** [comment]
It would make sense to have females be larger, as this does occur in many species
