### ISSUE TITLE
The Cyclops... Is this mob the mob we all waited for?

### ISSUE THREAD

**Issue by AguilaDaddy** [AlexModGuy/Ice-and-Fire-Suggestions#165]
The Cyclops mob.
This mob is very special, since it's one of the most tallest and strongest mobs in the game for now and for a while more- Besides the dragon. This creature deserves more attention and some tweaks.
The cyclops mob is a 3 block width and 8 blocks high monster. It can run faster than a player with Speed III, and their attacks are incredibly damaging, which makes it the second most dangerous and powerful mob we will have in the next 3 updates.
This is a great mob. There are so many things this mob could offer us other than their great challenging fight... but some of these things have not been added by the developers to the game. And I write this for them to see how could they improve this mob in so many ways as a feedback, if so they wish!

My first point is about the cyclops AI.
Cyclops are supposed to take care of their sheep and to protect them. That is why the sheep follow him. But why does he takes care of the sheep? Well, simple, it's food, and their wool and meat are tradable to other cyclops or even humans. This is what takes me to my next point- Cyclops behavior should be improved.
The cyclops attack the humans as if it was for fun. But actually, a cyclops isn't a zombie or a creeper- They are humanoid races, that in the greek mythology, had civilizations and lived close to each others, making it possible to trade. They actually think! So they may know if it's convenient to trade with a human or to kill him. So I suggest them only killing humans in the next situations: When they don't accept their trades, or when they are hurt. If a cyclops is hungry they can kill a human too, but why then would they have their sheep? Intelligent beings can understand each other! Somewhat like pixies and humans, pixies sometimes steal from humans, but they live in small towns! So I suggest cyclops killing humans only when angry or hungry, making it some kind of neutral-agressive mob. Another thing is that they could sleep too, so if a human approaches and notices they are asleep, they will try to open chests, but this can wake up the asleep giant!

Next point to mention. Cyclops spawning and location.
In greek mythology, cyclops race appeared to live in a far away island, where they all had their small town. But for now it's impossible to code a cyclops spawning randomly in an island from what I have understood. I agree with the suggestion of making them and their dungeons spawn in plains, generating some kind of big stone ruin with traps in them, but the treasure would be worth it. Some ruin where the cyclops can have a stone sheep pen, and where they can sleep and hide while the player enters the place in search of valuable stuff. There should also be large entrances and exits for the cyclops to go out and in. But now, is going on an adventure to the cyclop's cave in the beach really worth it? I dont think so, except for some real random valuable item you might find in there.
Players need to be encouraged to visit and possibly fight a cyclop, so the chests should have much more interesting items. Big amounts of diamonds, obsidian, totems of undying, or perhaps even dragon armor. Of course with the meat and wool as an extra, but you know what I mean. So if they start stealing before trading with the giant monster they'd have to face them, and try to kill them.

Much more interesting that way, right? ;)

With this I conclude my suggestions and feedback on cyclops mob... I really hope you keep it in mind, because many of the users who plays with this mod are waiting to see a change and an improvement on this amazing creature. 
Thank you for reading!

**Comment by mser7** [comment]
Can't even kill a late stage 2
