### ISSUE TITLE
Idea for the cockatrice mob

### ISSUE THREAD

**Issue by unicorncatbug** [AlexModGuy/Ice-and-Fire-Suggestions#198]
I feel like u should be able to put some type of armor on the cockatrice, like maybe u can give it claws and depending on the material it’s made of (iron, gold, or diamond) will have it do different amounts of damage.

**Comment by RealisticMC73309** [comment]
giving it claws is a thing that is for certain wouldn't happen. The devs don't want to support the cruel reality of cockfighting.
