### ISSUE TITLE
Sitting Model Pose

### ISSUE THREAD

**Issue by PlatinumFox** [AlexModGuy/Ice-and-Fire-Suggestions#20]
an animation or pose of sorts for when a dragon is in staying mode like it is sitting (raptorfarian once said something about using the sleeping position with the eyes open) and a swimming animation for the fire dragon... maybe not so much swimming since they don't swim but maybe a floating animation so fire dragons don't just look like ther are walking on water

**Comment by LordDecay26** [comment]
^^ i agree... this would add a great deal more of... i guess a role play element? anyways yeah i think this should definitely be added!
