### ISSUE TITLE
Frost and Fire King Mini Boss.

### ISSUE THREAD

**Issue by mser7** [AlexModGuy/Ice-and-Fire-Suggestions#215]
A tribute to I/F devs Raptorfarian and Alexthe666, these are mini boss that will challenges players on their journey.
Packing 80 hp, while equipped with their own respective armors that stronger than iron but weaker than diamond, they have natural regen, they fight with respective dragon blood sword.
Special ability: The Fire King can summon columns of fire that set the player on fire, damaging and obstruct their screen, he is immune to fire damage,. On the other hand, the Frost King has Frost Walker ability as well as put out nearby flames and emit a frozen aura that slowed down his opponent, if set on fire, he will be extinguished extremely quick.
Their respective structures are generated in biomes that match the elemental kings. The Fire Temple generated in fiery colored biome called the mesa, it generated in high hills, and the Frozen Temple generated where the ice has sprouted from the Earth, in the Ice Spikes biome. These temple have only one main room with one main door, the main room contain a stairway that lead down to the King's throne room, where the King patiently awaiting their challenger.
Reward: Upon defeating them, the King spawn a treasure chest in where he died, the chest have the blast resistance of obsidian to prevent being destroyed, it act like normal chest but with a more glamorous texture, it can only be mined with obsidian mining tools and cannot form a double chest. The chest contain useful and valuable loots, but there is one unique drop that stand out, such as a Red Fire Dragon Egg and Blue Ice Dragon Egg, a Fire King armor set that grant Fire resistance when fully equipped, and Frost King armor that put out flames with auto fire extinguish once the wearer is on fire, the boots also has natural Frost Walker. The final loot, is a special hippogryph egg, for the Fire King, a special Fiery Hippogryph and a Snowy Hippogryph for the Frost King, these hippogryphs are unique and cannot be found in the wild, the player however has to hatch it and wrangle it like other hippogryphs.

**Comment by mser7** [comment]
You should know about the special hippogryphs *wink*

**Comment by mser7** [comment]
I forgot to add that there is only one type of special loot generated randomly. The chest will contain either several armor pieces, a dragon egg or a hippogryph egg, raid another temple if you want to try again for another loot.

**Comment by alexgaudet** [comment]
maybe the fire king armor could also melt or reiste and ice damage?

**Comment by mser7** [comment]
Yes
