### ISSUE TITLE
Tamed dragons home points

### ISSUE THREAD

**Issue by GundunUkan** [AlexModGuy/Ice-and-Fire-Suggestions#23]
There could be a golden statue or totem of some sort, which when binded to a tamed dragon, could be placed down and act as the dragon's home point, around which he'll roam like a wild one does around his lair. Or simply an interface option to set the dragon's home point much like an MCA villager.

**Comment by tillasiren** [comment]
Would make it ideal, to not lost a dragon in the infinite world
