### ISSUE TITLE
Stop Dragon growing

### ISSUE THREAD

**Issue by Natrukei** [AlexModGuy/Ice-and-Fire-Suggestions#248]
Be able to stop the dragon from getting any bigger by either:
- feeding him Lilys, mixtures, hearts or blood. The opposite element to stop and the same element to reenable growth. 
--This would start giving Problems for new types of dragons, as you would need to find new counterparts to them.
-So the other way is to add an Item like an everstone (inspired by Pokémon) to either feed them or (what I would prefer) to place in a GUI slot.

**Comment by AlexModGuy** [comment]
will be in 1.5.2
