### ISSUE TITLE
Sirens 

### ISSUE THREAD

**Issue by AeterniRozu** [AlexModGuy/Ice-and-Fire-Suggestions#26]
A Siren is a creature most known from greek mythology , able to lure sailors into their deaths by producing a song that sway even the most prepared of people . ~ 
  Spawns : In the ocean on little rocky islands ( In groups ??? )
  Abilities : Makes a singing noise whenever a player is near and automatically makes the player walk move towards them ( Controls player movement ) 
  Slashes with claws ( or really sharp nails ) as their way to kill players , and or bites
  Looks : Like a distorted mermaid , open to different perceptions 
  ( Just an idea I had when I saw this mod , I personally am obsessed with the greek stories and find them an amazing way to spend time if bored )
  Ways to counter the song : Maybe some type of earmuffs or earplugs ( Wax ???? )

**Comment by AlexModGuy** [comment]
We've already got mermaids and nagas planned.
