### ISSUE TITLE
A second use for the Dragon Horn. “Get Back Down Here!”

### ISSUE THREAD

**Issue by CraftyAngyl** [AlexModGuy/Ice-and-Fire-Suggestions#39]
There currently is a major problem where, regardless of whether or not a dragon is staying or allowed to wander, if a tamed dragon becomes air born it cannot be commanded to land and will remain air born.  In effect, if you accidentally dismount midair for example, you have just lost your dragon.  Unless you have cheats enabled, switch to creative, and chase it down midair.

My idea is to use the Dragon Horn like a horn to call it back.  Not just from the air, but to just call it closer whether wandering or staying so you don't have to chase it around.  Like a dog whistle.  If the dragon is already set to stay then stay is what it will do when it reaches you.  If it is set to wander then once it reaches you it will go back to wandering until it is told to stay, but at least now it is within reach.

First version.  When you first use a horn on a dragon that horn becomes bound to that dragon.  It can only be used on that dragon.  The reason for this is so you can use the horn to call a wandering or flying dragon to you.  You blow on the horn the same way you summon a dragon, but you don’t have to be aiming at a block to do it and it makes the sound of a low, deep horn with the same animation as when you summon a dragon.  The dragon bound to that horn will be drawn to you whether it is in flight or meandering on the ground somewhere.

If there are obstructions it will quickly give up trying to reach you or the calling will simply be canceled when an obstruction is encountered, to prevent your precious pet from smothering itself in a cliff for example.  So just relocate and try again or use the horn pick it up if it is within reach.

The second version of this is that any horn can be used to call closer any dragons bound to you.  If a dragon is out of its horn and you use a horn, any horn, the dragon will walk/ fly over to you.  Once within range and on the ground you can command it or stick it in its horn.  Again blowing on a horn to call a dragon would have the same animation as with summoning a dragon from the horn accompanied with the sound of a low, deep horn.

Using the horn to call your dragon over a distance only works if the dragon is of course within range.  Try it from too far away and it just won’t happen.  But I would hope that the range would be quite far.  Possibly as far if not further than the sounds of their wings.  So if you can hear them, they can hear you.

Any thoughts?

Typed this up while suffering a head cold, so if any of this reads weird now you know why...

**Comment by AlexModGuy** [comment]
closed with adition of dragon bone flute
