### ISSUE TITLE
Mob render distance config option

### ISSUE THREAD

**Issue by talhanation** [AlexModGuy/Ice-and-Fire-Suggestions#432]
for all your entities to see them from further away

because i can see minecraft entities from 128 blocks, and this mods entities only 32  blocks, 
they disappear very fast

**Comment by HadesDeadlyTom** [comment]
Yes, i think you should increase the entity render distance or maybe give us a config to do so ?

I would like to be able to see the dragons from further away. I have a big chunk render distance but generally i see the dragons too late ^^

I would love to be able to see the dragons from far away a little like in Skyrim when you can saw them far in the distance.

The mod is really good, i like the quality and variety of the creatures !

**Comment by HadesDeadlyTom** [comment]
The new render distance for dragons in 1.8.0 is really good, i would like the sea serpents to have the same render distance as they are big mobs like the dragons and it would be perfect.
