### ISSUE TITLE
[wish list \ suggestion] Dragons with lazers

### ISSUE THREAD

**Issue by dustinmemoli** [AlexModGuy/Ice-and-Fire-Suggestions#442]
Wouldn't exactly fit with the current theme, but...

WISH LIST #2 
Dragons with Laserz
Could go crazy and add modular slots for power gen, power transfer, power storage, and even openmodularturrets. Would turn dragon into a flying automated defense system :) Because as children toys have taught us, lasers can make dinos and dragons even better lol.

**Comment by dustinmemoli** [comment]
https://i.ytimg.com/vi/b2q6ZZUToZc/hqdefault.jpg

**Comment by Xorbah** [comment]
Is this a troll? Lol

**Comment by dualinfinities** [comment]
I'm fairly sure this mod is based on mythology, not the Slayers anime.
