### ISSUE TITLE
Phoenix

### ISSUE THREAD

**Issue by gloryoftherain** [AlexModGuy/Ice-and-Fire-Suggestions#454]
I have heard many ideas for Phoenixes but I have an idea myself about them. I think phoenixes should be made by a rotten egg, ash and blaze rods and you need to throw the egg in lava, and a boss like phoenix should spawn and you have to fight it to low health (10 or less hp) and itll be tamed to you.

**Comment by tacoboi20** [comment]
Yeah that would be really cool... you could have a fire phoenix and an ice one, they could be the source of a resource called phoenix ash or something like that, that you attain every time the phoenix is reborn
