### ISSUE TITLE
Maybe a new mob idea?

### ISSUE THREAD

**Issue by EternalBlessing** [AlexModGuy/Ice-and-Fire-Suggestions#468]
So i have been enjoying this mod a lot i love Dragons they are my favorite fantasy animal and so I've been loving this a lot so far It seems so fantasy like. So my idea kinda went off if you have every played or seen Dragon's Dogma the Ogres obviously not exactly them but i was going based off that and maybe goblins that stay around the Ogre? What i was going to assume the Ogre would be some height of 8-16 blocks tall on surface with maybe a cave they can fit inside and they stay near that goblins also stay in. I also had an idea of Krakans if i spelled it correctly lol. What i thought of maybe with Ogres is they  can pick up trees and throw them at you or animals or maybe rocks. but they get obviously a club to fight with they are to dumb for anything else right? With goblins i kinda just assumed maybe spears, tiny shields. I don't really have to many ideas for Krakans because it seems like the only time you'd have to deal with it is when your in the water or i guess on a boat but there aren't big boats so it's kinda awkward i feel like they'd basically one shot you without having a giant boat. But i had an idea of an under water lair they they live in with semi air along the way inside hitting a giant open cave that they come an go from. Jeesh feel like pathing would be a bitch a that point ... but hey ideas are ideas right? But that's all i got maybe maybe not ¯\_(ツ)_/¯

**Comment by MasterOfTheCats** [comment]
Krakens and Goblins are confirmed to be added in future updates. You should join the Discord server if you’d like to know what’s gonna be added.

**Comment by BugmanBugman** [comment]
Trolls and Cyclops kind of already fit that niche
