### ISSUE TITLE
Ability to Make Dragon Bones and flesh into Dragon Meal

### ISSUE THREAD

**Issue by colejagdtiger** [AlexModGuy/Ice-and-Fire-Suggestions#50]
It would be nice to be able to use dragon bones to make dragon meal, perhaps using dragon flesh and bones you could create around 4 dragon meal. This would be a nice way to use extra dragon bones, especially seeing as it takes tons of dragon meal to grow you dragon.

**Comment by AlexModGuy** [comment]
Tell me; do you crush up dog bones into dog chow and give it to your dog? Doesn't something seem a bit off by that?

**Comment by colejagdtiger** [comment]
Yeah I do know that it is cannibalism, however I looked past that seeing as dragons are reptiles, and some reptiles eat their own newly hatched children so that only the strong survive.

**Comment by WilliamBlaze** [comment]
that usually implies the fact that the hatchling being eaten is too sickly to survive anyways. also; dragons have been known in most myths to practices some pretty unorthodox stuff so; cannibalism doesn't feel to far fetched at the very least. heck; there are stories of all sorts of animals that have been intentionally fed the meat of their own species by humans just to train them to have that instinct to hunt down their own kind and kill it without question, as sick of a practice as that might seem in the real world view of things, it has proven effective in the past in some cases with other species, and you forget; were hatching and raising them ourselves, who's to say an evil person wouldn't do this? - the freedom to do so should be up to the player. 

-- if there were to ever be some sort of moral system included with the raising of the creatures in this mod, i would imagine this method of feeding would cause one to create "evil/demonic" variants of the dragons their raising. but i digress, its up to the creators to take any though on this.
