### ISSUE TITLE
Feedback: Mobs  shouldn't spawn in dragon caverns

### ISSUE THREAD

**Issue by Dyzard** [AlexModGuy/Ice-and-Fire-Suggestions#512]
Mobs  are very annoying when fighting dragons in caverns, not only there is so many of them, you also get weakness effect from the dragon, and even more, multiple trolls nearly always spawn here, not only they have 50 hp, but they also regenerate, plus you have to kill them with a weakness effect on yourself. And making caverns bigger in a recent update didn't help with these issues at all. Fighting mobs shouldn't even be a part of a fight against a dragon.

**Comment by TytosB** [comment]
doesnt the dragon fire being spit everywhere incenerate them in like 2 seconds though? by the time im done fighting a level 5 dragon the entire cave is lit up like the fourth and everything else that was in there is ashes.

**Comment by AlexModGuy** [comment]
dupe
