### ISSUE TITLE
[New Creature] The Drake: Very Long 

### ISSUE THREAD

**Issue by Thunderwolf0** [AlexModGuy/Ice-and-Fire-Suggestions#515]
Appearance 
A much smaller version of a dragon. These would have 4 legs and 2 wings. They'd be around the size of a baby dragon for the most part and maybe a larger rarer/older version. Coming in the same color and element variants as their larger cousins the dragons (Ice, fire, maybe lightning)

Stats
Base health: 60
Bite attack: 6
Scratch attack: 3
Breath attack (Per second of exposure): 5 + element (Burn or frozen)
Dive bomb: 8

Wild behavior
Drakes are unintelligent reptilian beasts that attack almost anything (Besides dragons, cyclopes, sea serpents, hydra, and other large beasts friendly or not). They will travel alone or in small groups with an alpha (The older version). With their low intelligence, drakes close their eyes while attacking which can result in them hitting each other frequently and can be observed infighting with their packs (Normally the alpha will show why they're in charge and can pacify/unite the smaller ones meaning the Alphas have a good influence over their packs) They are often found spruce forests (Any forest primarily made of spruce trees not just the biome), taigas, extreme hills, or mountains.
They possess several attacks: 
Their main attack is a scratch or bite 
Their secondary attack is a breath attack
The larger variants while in berserker mode will have damage buffs, resistance, and can be seen dive bombing targets. 

Taming method:
To tame, one must show the drake whose boss by lowering the drakes' health then force feed them a type of feed. Alphas cannot be tamed and will get a buff when at a lower health levels as they get more dangerous. In packs, the alpha must be killed before one may tame drakes.The feed can be crafted with one golden apple, 4 bones, and 4 eggs.  
 
Tamed behavior
The normal sized ones can be shoulder mounted and with a press of a key can spew out a breath attack, they can also act like vanilla minecraft wolves (They won't actively fly during attacks but will fly whilst following to balance for PVP or togglable in configs). Similar to a cockatrice they can be set to patrol an area. The larger drakes can act like Elytra on one's back (Maybe have powered flight: As either a config option or as a unchangeable game feature). They can be bred with any dragon flesh or the respective lily mixtures. 
 
Extra notes/concepts:
Their breath attack cannot cause any ice spikes, charred blocks, or frozen blocks. However, ice drakes' breath while on one's back can freeze water in front of the player (I believe this can be relatively easy to code by taking the Frost walker code and applying it to the drakes). This can be toggled in configs
Fire drakes can be stationed by somebody's furnace and can power it (In config it can be toggled to affect both ores and food, just one of the two, or not at all). Perhaps with tinker's construct they can power smelteries.
They will still attack gorgons, however can't be petrified making them another possible counter to gorgons. (As they close their eyes whenever attacking) This can be toggled in configs.
Unlike dragons, drakes can ally themselves with other elements.
Tamed drakes will still flee from wild dragons, cyclopes, and other large animals. This should be able to be toggled in configs
If drakes of any size are near an Amphithere, the Amphithere can take control over the drake pack. Alternatively, this could be a cockatrice. (Not definite just a concept)
Tamed drakes shoulder mounted will dismount the player to get away from larger animals. However, with exception they will not dismount and flee from hydras with a player and instead can halt head growth. Maybe only fire drakes or maybe both.

**Comment by AlexModGuy** [comment]
no new types of dragon
