### ISSUE TITLE
Pixie Dust for Pacifists (and other pixie suggestions)

### ISSUE THREAD

**Issue by PiordaNautor** [AlexModGuy/Ice-and-Fire-Suggestions#520]
If the player does not want to harm pixies (more than they need to), Befriended Pixies should randomly drop and generate Pixie dust every so often. Maybe just less (or just as) often than Jarred Pixies.

Also, Pixies should be seated with empty hands (like with Cockatrices) as opposed to any time. It's a bit troublesome to occasionally lose your friend while using some form of Right Click spam.

**Comment by AlexModGuy** [comment]
put them in jars
