### ISSUE TITLE
Idea for new dragon forge mechanic as well as new recipes

### ISSUE THREAD

**Issue by kihgy** [AlexModGuy/Ice-and-Fire-Suggestions#540]
New recipe:
Fire dragon forge:
Basically a smeltery with dragon fueling
Ore doubling
Turning normal dirt, gravel, stone into charred version...

Ice dragon forge
Turn normal dirt, gravel, stone into the frozen versions
Turn normal water bucket into ice

New mechanic:
Dragon forge now have two output slot, that is so you can procced as twice as fast as normal furnaces, but only for recipes that require one input slot, for example, ore smelting, by filling the two slots with the same ore, the output ingots is put in both slots, indicating the forge can proceed both input slots at the same time
Automation: get the item out with a hopper underneath, and in by hoppering from the top, or the sides.

**Comment by AlexModGuy** [comment]
see, i wanted to do something like this originally, but it makes the fire dragon forge entirely more valuable than the ice dragon one.
