### ISSUE TITLE
item idea 

### ISSUE THREAD

**Issue by azuichh** [AlexModGuy/Ice-and-Fire-Suggestions#606]
an object that would bring back the lost dragon

description for the bestiary : the sound produced by this object is able to bring back the dragon even the furthest to the foot of their master, but I have the impression that the dragon is insensitive to this melody when it is in staying mode

here is an example of the object: ![Capture d’écran (293)](https://user-images.githubusercontent.com/54085530/70579720-c070ca00-1bb1-11ea-8126-8d760e71361a.png)

name: golden flute 

craft: ![Capture d’écran (294)](https://user-images.githubusercontent.com/54085530/70580112-f2cef700-1bb2-11ea-94c8-22015d6296ef.png)

I think the idea is relevant for the following reason: 
-many people lose their dragon by letting them wander
-if we die on his dragon we can bring him back

**Comment by AnasterianSunstrider** [comment]
I support this

**Comment by azuichh** [comment]
I forgot that this idea was still there, alex added crystals that have the same use as this item idea so i will close that
