### ISSUE TITLE
Suggestion for Dragons Staying

### ISSUE THREAD

**Issue by Frosty8-0** [AlexModGuy/Ice-and-Fire-Suggestions#61]
The Dragon should have a option to stay.  When set to stay the dragon will only move in a range of 20-30 blocks from where it was set to stay.

**Comment by Wolf7104** [comment]
You can order a dragon to stay, but it will stay in one position. But the idea is cool, I'll like to be able to set my dragon to limited wandering of some kind.

**Comment by Frosty8-0** [comment]
=)

**Comment by Frosty8-0** [comment]
Wait, you can set a dragon to stay?!

**Comment by Frosty8-0** [comment]
Nvm I feel stupid xD
