### ISSUE TITLE
Suggestion for Dragons Following

### ISSUE THREAD

**Issue by Frosty8-0** [AlexModGuy/Ice-and-Fire-Suggestions#62]
Dragon should have an option to follow their partner.  (The player that tamed the Dragon)
When set to follow, they would follow their partner with about a 10-15 range of wandering.

**Comment by Frosty8-0** [comment]
And when set to follow they should attack any mob that attacks its partner.

**Comment by AlexModGuy** [comment]
We don't have this because we prefer the dragon not to be a glorified wolf.

**Comment by NoahMeh** [comment]
A Dragon is not a slave!!!
