### ISSUE TITLE
Dragon Sexes

### ISSUE THREAD

**Issue by AlexModGuy** [AlexModGuy/Ice-and-Fire-Suggestions#63]
LatentDesire commented 9 days ago

As a key feature of the mod is getting your own dragon, and the eggs to get dragons are only dropped from female dragons, there should be some ways to differentiate male and female dragons. My suggestion, female dragons have less horns on their head, or smaller ridges down their backs.

Another possible update to the dragon models is to have some way of being able to tell when a dragon has reached sexual maturity. Perhaps the horns only come in when dragons are able to breed.
@LatentDesire
LatentDesire commented 9 days ago

Oh, there should also be some worthwhile reward for fighting a stage five male dragon as well. (As I'm sure some may be disappointed that the struggle they've had fight a dragon in hopes of an egg.)

**Comment by Wolf7104** [comment]
Maybe from the male dragon you can get more treasures. From what I've read, male dragons collect treasures primarily to attract females, and in some cases - to lay on them in hopes they will stick to their weak belly skin.

**Comment by Wolf7104** [comment]
And also they collect gemstones. There could be piles of different gemstones in a male's cave.
Great feature to have, will be to be able to collect special treasures from a male dragon's layer and offer them to the female, so she gives you an egg or two, without needing to kill her. This will be cool for people who don't want to slay the mother every time they want to have their own dragon.

**Comment by LordDecay26** [comment]
my suggestion is have stage 5 male dragons collect piles of gemstones. a good way to tell if they have an egg (reached sexual maturity) would be if the horns and ridges along its back were longer... like huge spikes coming out of the dragon. this would 1.) make it more worthwhile finding and fighting a stage 5 and 2.) make it easier to find pregnant female dragons carrying eggs.

**Comment by WilliamBlaze** [comment]
The one probe's "TOP Add-on" mod already lets a user tell what gender and stage a dragon is by looking at them with a probe. i'm not saying this isn't a good idea though. maybe the males should have longer horns or maybe spiked tails. something obvious from a glance if were worried about telling what dragon is what without use of outside sources.
