### ISSUE TITLE
Lightning in Savannahs

### ISSUE THREAD

**Issue by Spinogaming** [AlexModGuy/Ice-and-Fire-Suggestions#833]
Maybe with this mod lightning should spawn in savannahs? Idk

**Comment by BigMamaSlama** [comment]
thats already whats happening.

**Comment by Spinogaming** [comment]
Bruh, I don't mean the dragons, i mean lightning as in lightning bolts, so when a thunderstorm happens

**Comment by Spinogaming** [comment]
Made better description on a new suggestion
