### ISSUE TITLE
Different Subspecies of Dragons

### ISSUE THREAD

**Issue by CommandBlockGuru** [AlexModGuy/Ice-and-Fire-Suggestions#840]
I noticed while fighting a fire dragon that the dragon was a wyvern. I was wondering if maybe there could be other types, too? Kind of like how you put the amphithere (I don't know if I spelled that right), which is a dragon with no legs. I was thinking more along the lines of standard dragons being a remodel of the ones now, wyverns being some type of smaller dragon that's the fastest flying creature in the game, and drakes, witch are the strongest fighting wise, but flightless. Maybe the wyverns could spawn on mountains or just higher up areas, while the drakes can spawn in plains, savannas, anywhere flat. You could put them in some type of scenario like the amphithere has. Idk. I just thought this idea was nice and wanted to share it.

**Comment by BigMamaSlama** [comment]
the devs dont like calling them wyverns. they are just called dragons.

**Comment by CommandBlockGuru** [comment]
Yes, I know that wyverns are a type of dragon. And so are drakes. And amphitheres are technically a type of legless dragon.

**Comment by BigMamaSlama** [comment]
yes but i dont think they care about going into specifics of the dragons ice/fire/lightening dragons are the only ''dragons'' and amphitheres are amphitheres. theres no drakes or wyverns

**Comment by CommandBlockGuru** [comment]
Alright then. Thank you!
