### ISSUE TITLE
Suggestion for a legendary animal - Unicorn.

### ISSUE THREAD

**Issue by Alyaqdhans** [AlexModGuy/Ice-and-Fire-Suggestions#852]

**Comment by ElijahTommy** [comment]
good idea

**Comment by ElijahTommy** [comment]
Here's some concept art for you

![Untitled95_20200825212150](https://user-images.githubusercontent.com/70062464/91168540-26d65200-e719-11ea-9a19-7a3014a7ec52.png)

**Comment by Alyaqdhans** [comment]
Maybe making it rainbow will be cooler?

**Comment by Alyaqdhans** [comment]
Something like that? XD you can make it even better, this is just a sketch.
![IMG_20200829_192121](https://user-images.githubusercontent.com/58079015/91640233-036b1a00-ea2d-11ea-8298-a6355e18e8d2.png)
