### ISSUE TITLE
Mammoths, Shadowcats & Giants

### ISSUE THREAD

**Issue by Legoldin** [AlexModGuy/Ice-and-Fire-Suggestions#97]
Mammoths, Shadowcat and Giants. you're gonna add Trolls, right? 
So, why not add Giants? They is like Trolls, but, they can gonna have Mammoths like in the book "Storm of Swords" 
I gonna try to make a simple model of they for demonstration

**Comment by AlexModGuy** [comment]
Giants have already been crossed out, Cyclops will be practically the same mechanic-wise.
For mammoths, those are real animals that have just died out. If you want those go check out JurassiCraft or Fossils Revival.
And Shadowcats? what would be different from them and polar bears in vanilla?
